In [1]:
# Collection data types in Python
# str - sequence of characters
# list - ordered, mutable collection of items
# tuple - ordered, immutable collection of items
# set - unordered collection of unique items, mutable
# dict - collection of key-value pairs

In [2]:
my_list = [10, 100, 25, 36]
my_list

[10, 100, 25, 36]

In [3]:
set_1 = {10, 100, 25, 36, 10, 25}
set_1

{10, 25, 36, 100}

In [8]:
set_1 = {1, 2, 3, 4, 5}
# set_2 = {4, 5, 6, 7, 8, {1, 2, 3}}  # This will raise an error because sets cannot contain other sets
set_2 = {4, 5, 6, 7, 8, (1, 2, 3)}  # Using a tuple instead
# set_3 = {1, 2, 3, 4, 5, [1, 2, 3]}  # This will raise an error because sets cannot contain lists  
set_2

{(1, 2, 3), 4, 5, 6, 7, 8}

In [9]:
True if 12 % 2 == 0 else False

True

In [10]:
# functions

def is_even(num):
    return True if num % 2 == 0 else False
is_even(13)

False

In [11]:
# Types oif arguments in functions
# positiona arguments, keyword arguments, default arguments, variable-length arguments, lambda arguments

In [13]:
def ex():
  print("Hello World")

In [15]:
def my_funct(x):
  return x()

# my_funct(lambda: 5 + 5)
my_funct(ex)

Hello World


In [18]:
def func(*args, **kwargs): # *args - positional arguments(variable length variable), **kwargs - keyword arguments
    print("Positional arguments:", args)
    print("Keyword arguments:", kwargs)

In [19]:
func(1, 2, 3, name="Alice", age=30)

Positional arguments: (1, 2, 3)
Keyword arguments: {'name': 'Alice', 'age': 30}


In [20]:
def func(**kwargs):
  return kwargs

func(name="Alice", age=30)

{'name': 'Alice', 'age': 30}

In [24]:
def ff(**kwargs):
  return kwargs

In [27]:
d1 = {'A': 1, 'B': 2, 'C': 3}
ff(**d1)

{'A': 1, 'B': 2, 'C': 3}

In [28]:
# Lambda functions - anonymous functions, single expression functions

In [30]:
add_1 = lambda x, y: x + y

In [31]:
add_1(10, 20)

30

In [32]:
# mostly it is used with functions like map, filter, reduce

In [33]:
# What is map, filter, reduce
# map - applies a function to all the items in an input list
# filter - filters the items in an input list based on a condition
# reduce - applies a rolling computation to sequential pairs of values in a list

In [37]:
my_list = [1, 2, 3, 4, 5]
# my_list.filter(lambda x: x % 2 == 0)
# filter even numbers from my_list
list(filter(lambda x: x % 2 == 0, my_list))  # [2, 4]

[2, 4]

In [38]:
list(map(lambda x: 'Even' if x % 2 == 0 else 'Odd', my_list))  # ['Odd', 'Even', 'Odd', 'Even', 'Odd']

['Odd', 'Even', 'Odd', 'Even', 'Odd']

In [39]:
reduce(lambda x, y: x + y, my_list)  # 15

NameError: name 'reduce' is not defined

In [41]:
import reduce

ModuleNotFoundError: No module named 'reduce'

In [40]:
# example of reduce to find the maximum element in a list
# reduce(lambda x, y: x if x > y else y, my_list)  #

NameError: name 'reduce' is not defined

In [44]:
# find the product of all elements in a list using reduce
reduce(lambda x, y: x * y, my_list)  # 120

NameError: name 'reduce' is not defined

In [46]:
from functools import reduce

In [47]:
reduce(lambda x, y: x + y, my_list)  # 15

15

In [48]:
# Try/catch blocks - exception handling

In [53]:
a = 100
b = 0

try:
    result = a / b
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except Exception as e:
    print("An error occurred:", str(e))
finally:
    print("Execution completed.")

Error: Division by zero is not allowed.
Execution completed.


In [54]:
# Question paper

# What is type casting? Explain with examples.
# Type casting is the process of converting a variable from one data type to another. For example:
# Converting an integer to a string
num = 10
str_num = str(num)  # '10'
# Converting a string to an integer
str_value = "25"
int_value = int(str_value)  # 25
# Converting a float to an integer    
float_value = 10.75
int_float = int(float_value)  # 10  
# Converting an integer to a float
int_value = 20
float_value = float(int_value)  # 20.0
# Converting a string to a float
str_value = "15.5"
float_value = float(str_value)  # 15.5    

In [55]:
# What is the difference between a list and a tuple?
# A list is an ordered, mutable collection of items, while a tuple is an ordered, immutable collection of items. Lists can be modified after creation (items can be added, removed, or
# changed), whereas tuples cannot be modified once they are created. Lists are defined using square brackets [], while tuples are defined using parentheses ().

In [58]:
# What do you understand by lambda functions? Provide an example.
# Lambda functions are anonymous functions defined using the lambda keyword. They can take any number of arguments but can only have a single expression. Example:
# A lambda function that adds two numbers
add = lambda x, y: x + y
result = add(5, 10)  # 15

#  Create a labm

my_list = [5, 8, 10, 20, 50, 100]
# sum of all the elements in the list using labmda
reduce(lambda x, y: x + y, my_list)  # 193

193

In [59]:
# Create a lamda function which wuill print the summ of all the elememts in a list
sum_all = lambda lst: reduce(lambda x, y: x + y, lst)
sum_all(my_list)  # 193

193

In [60]:
# What is the string and explain of string
# A string is a sequence of characters enclosed within single quotes (' '), double quotes (" "), or triple quotes (''' ''' or """ """). Strings are used to represent text data in Python. Strings are immutable, meaning they cannot be changed after they are created. Strings support various operations such as concatenation, slicing, and formatting.

In [61]:
# What are *agrs and **kwargs in Python functions?
# *args and **kwargs are used to pass a variable number of arguments to a function.
# *args allows a function to accept any number of positional arguments as a tuple.
# **kwargs allows a function to accept any number of keyword arguments as a dictionary.

In [63]:
# Explain the difference between pivot table and crosstab in pandas.
# A pivot table is a data summarization tool that allows you to aggregate and reshape data based on specified index and column values, often used for multi-dimensional analysis. 
# A crosstab, on the other hand, is a specific type of pivot table that is used to compute a simple frequency table of two or more categorical variables, typically used for contingency tables.

# Example for pivot table and crosstab
import pandas as pd 
data = {
    'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'B': ['one', 'one', 'two', 'two', 'one', 'one'],
    'C': [1, 2, 3, 4, 5, 6],
    'D': [10, 20, 30, 40, 50, 60]
} 
df = pd.DataFrame(data)
pivot_table = pd.pivot_table(df, values='D', index=['A'], columns=['B'], aggfunc='sum')
crosstab = pd.crosstab(df['A'], df['B'])  
print("Pivot Table:\n", pivot_table)
print("Crosstab:\n", crosstab)

Pivot Table:
 B    one  two
A            
bar  110   40
foo   30   30
Crosstab:
 B    one  two
A            
bar    2    1
foo    2    1


In [65]:
# How can we get a random number in Python?
# We can get a random number in Python using the random module. For example:
import random
random_number = random.randint(1, 100)  # Generates a random integer between 1 and 100
print(random_number)

# using numpy
import numpy as np
random_number_np = np.random.randint(1, 100)  # Generates a random integer between 1 and 100
print(random_number_np)

35
80


In [67]:
# What is map and reduce functions in Python? Provide examples.
# The map function applies a given function to all items in an input list (or any iterable) and returns a map object (which can be converted to a list). Example:
my_list = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x ** 2, my_list))  # [1, 4, 9, 16, 25]
# The reduce function applies a rolling computation to sequential pairs of values in a list. Example:
from functools import reduce
sum_of_elements = reduce(lambda x, y: x + y, my_list)  # 15
sum_of_elements

15

In [69]:
# How is vstack different from hstack in numpy?
# In NumPy, vstack (vertical stack) is used to stack arrays vertically (row-wise), while hstack (horizontal stack) is used to stack arrays horizontally (column-wise). For example:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
vstacked = np.vstack((array1, array2))
hstacked = np.hstack((array1, array2))
print(vstacked)
print(hstacked)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [70]:
# How is sorted() and sort() can be used with list in Python? Give an example.
# The sorted() function returns a new sorted list from the elements of any iterable, while the sort() method sorts the list in place and returns None. Example:
my_list = [5, 2, 9, 1, 5, 6]
sorted_list = sorted(my_list)  # [1, 2, 5, 5, 6, 9]
print("Sorted list using sorted():", sorted_list)
my_list.sort()  # my_list is now [1, 2, 5, 5, 6, 9]
print("Sorted list using sort():", my_list)

Sorted list using sorted(): [1, 2, 5, 5, 6, 9]
Sorted list using sort(): [1, 2, 5, 5, 6, 9]


In [ ]:
# 3a. James Deen is an investor specializing....


3.a. James Deen is an investor specializing in the Technology Domain. James purchases stock in successful technology companies using a stockbroker and later sells them at a profit margin

As part of his investment portfolio, James purchased 2000 units of stock in Google LLC worth $80,000 ($40 apiece) in the month of November, 2019. The stockbroker charged 3% commission on the total purchase value of the stocks.A month later, James sells his entire stock holding in Google LLC for $42.75 apiece. He pays a commission of 3% on this transaction as well to his stockbroker.

**Write a Python program that returns the following output:**

1. The cost of purchasing the entire stock holding in Google LLC

2. The amount of money paid in commission during the purchase

3. The selling price of the entire stock holding in Google LLC

4. The amount of money paid in commission during the sale

5. The profit margin made by James in the entire transaction (purchase & sale, including commissions paid)

In [78]:
(80000 + 2400.0) - (85500.0 - 2565.0)

-535.0

In [72]:
# Given data
units = 2000
purchase_price_per_stock = 40
selling_price_per_stock = 42.75
commission_rate = 0.03  # 3%

# 1. Cost of purchasing the entire stock holding
purchase_cost = units * purchase_price_per_stock

# 2. Commission paid during purchase
purchase_commission = purchase_cost * commission_rate

# 3. Selling price of the entire stock holding
selling_value = units * selling_price_per_stock

# 4. Commission paid during sale
selling_commission = selling_value * commission_rate

# 5. Profit margin (after considering both commissions)
profit = (selling_value - selling_commission) - (purchase_cost + purchase_commission)

# Display the results
print("1. Cost of purchasing the entire stock holding: $", round(purchase_cost, 2))
print("2. Commission paid during purchase: $", round(purchase_commission, 2))
print("3. Selling price of the entire stock holding: $", round(selling_value, 2))
print("4. Commission paid during sale: $", round(selling_commission, 2))
print("5. Profit margin (after all commissions): $", round(profit, 2))


1. Cost of purchasing the entire stock holding: $ 80000
2. Commission paid during purchase: $ 2400.0
3. Selling price of the entire stock holding: $ 85500.0
4. Commission paid during sale: $ 2565.0
5. Profit margin (after all commissions): $ 535.0


3b. 
i) You need to maintain an inventory of products in the online store. Create a Python dictionary named product_inventoryto store the product names as keys and their corresponding quantities as values. (2 Marks)

ii)You have received a new shipment of products. Write a Python function named update_inventory  that  takes  the  current  product_inventory  and  a  dictionary representing  the  new  shipment  with  product  names  and  quantities.  The  function should update the inventory with the new shipment quantities. (6 Marks)

iii)You want to offer discounts on certain products. Write a Python function named apply_discount  that  takes  the  current  product_inventoryand  a  dictionary representing  the  discounted  products  with  their  new  prices.  The  function  should update the inventory with the discounted prices. (7 Marks)

In [79]:
# i) Create a dictionary to store product names and their quantities
product_inventory = {
    "Laptop": 10,
    "Smartphone": 25,
    "Headphones": 50,
    "Keyboard": 15,
    "Mouse": 20
}


In [80]:
# ii) Function to update inventory with new shipment quantities
def update_inventory(current_inventory, new_shipment):
    for product, quantity in new_shipment.items():
        # If product already exists, add to the existing quantity
        if product in current_inventory:
            current_inventory[product] += quantity
        else:
            # Add new product to inventory
            current_inventory[product] = quantity
    return current_inventory


In [81]:
new_shipment = {
    "Laptop": 5,
    "Smartwatch": 10,
    "Mouse": 8
}

product_inventory = update_inventory(product_inventory, new_shipment)
print("Updated Inventory:", product_inventory)


Updated Inventory: {'Laptop': 15, 'Smartphone': 25, 'Headphones': 50, 'Keyboard': 15, 'Mouse': 28, 'Smartwatch': 10}


In [87]:
# Modified inventory with quantity and price
product_inventory = {
    "Laptop": {"quantity": 10, "price": 80000},
    "Smartphone": {"quantity": 25, "price": 30000},
    "Headphones": {"quantity": 50, "price": 2000},
    "Keyboard": {"quantity": 15, "price": 1500},
    "Mouse": {"quantity": 20, "price": 800}
}

# iii) Function to apply discounts on certain products
def apply_discount(current_inventory, discounted_products):
    # Update the inventory with discounted prices
    # current_inventory.update(discounted_products)
    for product, new_price in discounted_products.items():
        if product in current_inventory:
            current_inventory[product]["price"] = new_price
    return current_inventory

discounted_products = {
    "Laptop": 75000,
    "Headphones": 1800
}

product_inventory = apply_discount(product_inventory, discounted_products)
print("Inventory after applying discounts:", product_inventory)


Inventory after applying discounts: {'Laptop': {'quantity': 10, 'price': 75000}, 'Smartphone': {'quantity': 25, 'price': 30000}, 'Headphones': {'quantity': 50, 'price': 1800}, 'Keyboard': {'quantity': 15, 'price': 1500}, 'Mouse': {'quantity': 20, 'price': 800}}


In [83]:
new_shipment

{'Laptop': 5, 'Smartwatch': 10, 'Mouse': 8}

In [86]:
for prod, quant in new_shipment.items():
    print(prod, quant)

Laptop 5
Smartwatch 10
Mouse 8
